Algoritmo "Exibir Mensagem"
// Disciplina   : [Lógica de Programação e JavaScript]
// Professor   : Jailson
// Descrição   : Exibir uma Mensagem
// Autor(a)    : Geovanna Souza Cordeiro Silva
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Alanys - Poá")
Escreval("Equipe 04")
Escreval("Abner")

Fimalgoritmo