Algoritmo "Repita div por 4"
// Disciplina   : [Lógica de Programação e JavaScript]
// Professor   : Jailson
// Descrição   : Apresentar todos os números divisíveis por 4 que sejam menores que 200
// Autor(a)    : Geovanna Souza Cordeiro Silva
// Data atual  : 06/09/2021
Var
// Seção de Declarações das variáveis
cont:inteiro

Inicio
repita
      se cont mod 4 = 0 entao
      escreval (cont)
      fimse
      cont<-cont+1
      ate cont>199
Fimalgoritmo
