Algoritmo "Valores Impares"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Apresentar todos os valores numéricos inteiros ímpares situados na faixa de 0 a 20
// Autor(a)    : Geovanna Souza Cordeiro Silva
// Data atual  : 06/09/2021
Var
   cont:inteiro

Inicio
   para cont de 0 ate 20 passo 1 faca
      se (cont mod 2 = 1) entao
         escreval(cont)
      fimse
   fimpara
Fimalgoritmo